name: Test
on: [workflow_dispatch]
jobs:
   job-1:
   runs-on: ubuntu-18.04
   steps:
     - name: Teste1
       run: npm teste
   job-2:
   runs-on: ubuntu-20.04
   steps:
     - name: Teste2
       run: npm teste    
   job-2:
   runs-on: ubuntu-22.04
   steps:
     - name: Teste3
       run: npm teste
